nome = str(input('Digite o nome: '))
cpf = int(input('Digite o cpf: '))
rg = int(input('Digite o numero do rg: '))
nasc = int(input('Digite a data de nascimento: '))
sexo = str(input('Digite o sexo: '))
peso = float(input('Digite o peso: '))
sangue = str(input('Digite o tipo sanguineo: '))
renda = float(input('Digite a sua renda: '))
endereco = str(input('Digite o endereço: '))
tel = int(input('Digite o telefone: '))
cidade = str(input('Digite a cidade: '))
estado = str(input('Digite o estado: '))

print("\n")
print("+-+-"*15)

print(f'Nome: {nome}')
print(f'Cpf: {cpf}')
print(f'Rg: {rg}')
print(f'Data de nascimento: {nasc}')
print(f'Sexo: {sexo}')
print(f'Peso: {peso}')
print(f'Tipo sanguineo: {sangue}')
print(f'Renda: {renda}')
print(f'Endereço: {endereco}')
print(f'Cidade: {cidade}')
print(f'Estado: {estado}')